### ISSUE TITLE
why did not you want to use jade, mustache, lodash.template ?

### ISSUE THREAD

**Issue by jt3k** [Mitranim/statil#1]

**Comment by Mitranim** [comment]
Jade: too different from HTML, leads to non-portable code; not worth the bother.

Last I checked, Jade and Mustache both made the mistake of not embedding JS and inventing their own keywords and control structures. Templating systems that start as "logicless" inevitable evolve their own mini-scripting, which has a higher mental and implementation cost compared to simply embedding the host language as-is.

Lodash templating is great. It makes the right decision to just embed JS. It's also basically just a simple 100 LoC function, compared to the mountains of crap other templating systems consist of. Statil actually started off as a wrapper around it, adding support for referencing templates from inside each other, which is necessary for organizing layouts. I ended up switching to a slightly better, but still lodash-inspired [templating function](https://github.com/Mitranim/statil/blob/cc8c65ba2987d29e08e3d4858d2401742e33a7d4/lib/template.js) only a month ago.

Btw why you askin'?

**Comment by jt3k** [comment]
копался в gulpfile на одном из проектов и не понял зачем мы обрабатываем статические html при помощи Statil. Полез  разбираться и нашёл это репо

**Comment by Mitranim** [comment]
If there's just one HTML template and you don't like unnecessary dependencies, use lodash in gulp directly:

```js
const {Transform} = require('stream')

// ...

.pipe(new Transform({
  objectMode: true,
  transform(file, __, done) {
    const rendered = _.template(String(file.contents))()
    file.contents = Buffer.from(rendered)
    done(undefined, file)
  },
}))
```

**Comment by jt3k** [comment]
thanx, looks good.

One remark:
For unused variables, it's best to use empty braces.

In this case
1) an unused variable within the context will not be created
2) if we need to skip more than one argument, we do not deal with the naming problem)
```js
function lolo (a, {}, {}, d) {
  return a + d;
}

lolo(1,2,3,4) // => 5
```

**Comment by Mitranim** [comment]
Nice tip, thanks 🙂
